-- MySQL Script generated by MySQL Workbench
-- Wed Apr 22 16:04:55 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema psc_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema psc_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `psc_db` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `psc_db` ;

-- -----------------------------------------------------
-- Table `psc_db`.`login_attempts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psc_db`.`login_attempts` (
  `user_id` INT(11) NOT NULL AUTO_INCREMENT,
  `time` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `psc_db`.`members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psc_db`.`members` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(30) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `password` CHAR(128) NOT NULL,
  `salt` CHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `psc_db`.`partner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psc_db`.`partner` (
  `id_partner` INT NOT NULL AUTO_INCREMENT,
  `logo_img_path` VARCHAR(150) NOT NULL,
  `partner_name` VARCHAR(45) NOT NULL,
  `partner_website` VARCHAR(45) NULL,
  PRIMARY KEY (`id_partner`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psc_db`.`circolo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psc_db`.`circolo` (
  `id_circolo` INT NOT NULL AUTO_INCREMENT,
  `circolo_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`id_circolo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psc_db`.`sport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psc_db`.`sport` (
  `id_sport` INT NOT NULL AUTO_INCREMENT,
  `sport_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_sport`),
  UNIQUE INDEX `sport_name_UNIQUE` (`sport_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psc_db`.`event_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psc_db`.`event_type` (
  `id_event_type` INT NOT NULL AUTO_INCREMENT,
  `event_type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_event_type`),
  UNIQUE INDEX `event_type_name_UNIQUE` (`event_type_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psc_db`.`event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psc_db`.`event` (
  `id_event` INT NOT NULL AUTO_INCREMENT,
  `event_title` VARCHAR(100) NOT NULL,
  `event_date` DATE NULL,
  `event_description` MEDIUMTEXT NOT NULL,
  `event_flyer` VARCHAR(100) NULL,
  `sport` INT NOT NULL,
  `event_type` INT NOT NULL,
  PRIMARY KEY (`id_event`),
  INDEX `fk_event_sport1_idx` (`sport` ASC),
  INDEX `fk_event_event_type1_idx` (`event_type` ASC),
  CONSTRAINT `fk_event_sport1`
    FOREIGN KEY (`sport`)
    REFERENCES `psc_db`.`sport` (`id_sport`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_event_type1`
    FOREIGN KEY (`event_type`)
    REFERENCES `psc_db`.`event_type` (`id_event_type`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psc_db`.`sport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psc_db`.`sport` (
  `id_sport` INT NOT NULL AUTO_INCREMENT,
  `sport_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_sport`),
  UNIQUE INDEX `sport_name_UNIQUE` (`sport_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psc_db`.`event_gallery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psc_db`.`event_gallery` (
  `id_event_gallery` INT NOT NULL AUTO_INCREMENT,
  `gallery_name` VARCHAR(45) NOT NULL,
  `event_id_event` INT NOT NULL,
  PRIMARY KEY (`id_event_gallery`),
  INDEX `fk_event_gallery_event1_idx` (`event_id_event` ASC),
  CONSTRAINT `fk_event_gallery_event1`
    FOREIGN KEY (`event_id_event`)
    REFERENCES `psc_db`.`event` (`id_event`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psc_db`.`event_picture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psc_db`.`event_picture` (
  `id_event_picture` INT NOT NULL AUTO_INCREMENT,
  `picture_path` VARCHAR(45) NULL,
  `event_gallery_id_event_gallery` INT NOT NULL,
  PRIMARY KEY (`id_event_picture`),
  INDEX `fk_event_picture_event_gallery1_idx` (`event_gallery_id_event_gallery` ASC),
  CONSTRAINT `fk_event_picture_event_gallery1`
    FOREIGN KEY (`event_gallery_id_event_gallery`)
    REFERENCES `psc_db`.`event_gallery` (`id_event_gallery`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `psc_db`.`module`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `psc_db`.`module` (
  `id_module` INT NOT NULL AUTO_INCREMENT,
  `module_name` VARCHAR(45) NOT NULL,
  `file_path` VARCHAR(45) NOT NULL,
  `module_date` DATE NOT NULL,
  PRIMARY KEY (`id_module`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
